### ISSUE TITLE
Can't start the game, assertion failed

### ISSUE THREAD

**Issue by v4lley** [tsoding/nothing#659] opened 2019-01-23 16:47 UTC
after executing `./nothing ../levels/level-01.txt`
it doesn't start and gives me the following output:
```
[WARN] Could not find any Sticks of the Joy
/nothing/src/game/level_picker.c:103: level_picker_input: Assertion `the_stick_of_joy' failed
Stacktrace: 
./nothing(__trace_assert+0x29)[0x55a6cdd1a9f9]
./nothing(level_picker_input+0x47)[0x55a6cdd1ad07]
./nothing(main+0x342)[0x55a6cdd03d62]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fd5817982e1]
./nothing(_start+0x2a)[0x55a6cdd03f3a]
```

**Comment by rexim** [comment] 2019-01-23 17:58
Looks like a duplicate of #650

**Closed** 2019-01-23 18:07 UTC
Labels: duplicate
